DELETE FROM "Person";

CREATE TYPE "Role" AS ENUM ('STUDENT', 'TEACHER');

CREATE TYPE "Gender" AS ENUM ('MALE', 'FEMALE', 'OTHER');

ALTER TABLE "Person"
  ALTER COLUMN "role" DROP DEFAULT,
  ALTER COLUMN "gender" TYPE "Gender" USING ('MALE'::"Gender"),
  ALTER COLUMN "role" TYPE "Role" USING ('STUDENT'::"Role"),
  ALTER COLUMN "role" SET DEFAULT 'STUDENT';
